name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache git zlib1g-dev libffi-dev libssl-dev openjdk-17-jdk
        pip install --upgrade pip setuptools
        pip install "cython<3.0.0" buildozer

    - name: Build APK with Buildozer
      run: |
        yes | buildozer init
        sed -i 's/requirements = python3,kivy/requirements = python3,kivy,plyer/g' buildozer.spec
        sed -i 's/# android.permissions = INTERNET/android.permissions = ACCESS_FINE_LOCATION, ACCESS_COARSE_LOCATION, SYSTEM_ALERT_WINDOW, INTERNET/g' buildozer.spec
        sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
        yes | buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: bin/*.apk
